name: Multi-stage Firebase Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install, Build and Test
        run: npm i && npm run build && npm run test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: w9jds/firebase-action@v1.0.1
        if: success()
        with:
          args: deploy
        env:
          ## Joins the current branch name + prefix so that we can get the variables relative to the branch
          PROJECT_ID: ${{ secrets[join('firebase_project_', github['ref'])] }}
          FIREBASE_TOKEN: ${{ secrets[join('firebase_key_', github['ref'])] }}